/* GENERATED FILE; DO NOT EDIT */
@file:Suppress("unused", "PropertyName")

package de.pans.controllers

class CnanoKONTROL2 : Controller("nanoKONTROL2") {

    val F_COL1_FADER = ControllerKey("F_COL1_FADER", 0)
    val F_COL2_FADER = ControllerKey("F_COL2_FADER", 1)
    val F_COL3_FADER = ControllerKey("F_COL3_FADER", 2)
    val F_COL4_FADER = ControllerKey("F_COL4_FADER", 3)
    val F_COL5_FADER = ControllerKey("F_COL5_FADER", 4)
    val F_COL6_FADER = ControllerKey("F_COL6_FADER", 5)
    val F_COL7_FADER = ControllerKey("F_COL7_FADER", 6)
    val F_COL8_FADER = ControllerKey("F_COL8_FADER", 7)
    val F_COL1_ROTATOR = ControllerKey("F_COL1_ROTATOR", 16)
    val F_COL2_ROTATOR = ControllerKey("F_COL2_ROTATOR", 17)
    val F_COL3_ROTATOR = ControllerKey("F_COL3_ROTATOR", 18)
    val F_COL4_ROTATOR = ControllerKey("F_COL4_ROTATOR", 19)
    val F_COL5_ROTATOR = ControllerKey("F_COL5_ROTATOR", 20)
    val F_COL6_ROTATOR = ControllerKey("F_COL6_ROTATOR", 21)
    val F_COL7_ROTATOR = ControllerKey("F_COL7_ROTATOR", 22)
    val F_COL8_ROTATOR = ControllerKey("F_COL8_ROTATOR", 23)
    val B_COL1_S = ControllerKey("B_COL1_S", 32)
    val B_COL2_S = ControllerKey("B_COL2_S", 33)
    val B_COL3_S = ControllerKey("B_COL3_S", 34)
    val B_COL4_S = ControllerKey("B_COL4_S", 35)
    val B_COL5_S = ControllerKey("B_COL5_S", 36)
    val B_COL6_S = ControllerKey("B_COL6_S", 37)
    val B_COL7_S = ControllerKey("B_COL7_S", 38)
    val B_COL8_S = ControllerKey("B_COL8_S", 39)
    val B_PLAY = ControllerKey("B_PLAY", 41)
    val B_STOP = ControllerKey("B_STOP", 42)
    val B_REWIND = ControllerKey("B_REWIND", 43)
    val B_FORWARD = ControllerKey("B_FORWARD", 44)
    val B_REC = ControllerKey("B_REC", 45)
    val B_CYCLE = ControllerKey("B_CYCLE", 46)
    val B_COL1_M = ControllerKey("B_COL1_M", 48)
    val B_COL2_M = ControllerKey("B_COL2_M", 49)
    val B_COL3_M = ControllerKey("B_COL3_M", 50)
    val B_COL4_M = ControllerKey("B_COL4_M", 51)
    val B_COL5_M = ControllerKey("B_COL5_M", 52)
    val B_COL6_M = ControllerKey("B_COL6_M", 53)
    val B_COL7_M = ControllerKey("B_COL7_M", 54)
    val B_COL8_M = ControllerKey("B_COL8_M", 55)
    val B_TRACK_L = ControllerKey("B_TRACK_L", 58)
    val B_TRACK_R = ControllerKey("B_TRACK_R", 59)
    val B_SET = ControllerKey("B_SET", 60)
    val B_MARKER_L = ControllerKey("B_MARKER_L", 61)
    val B_MARKER_R = ControllerKey("B_MARKER_R", 62)
    val B_COL1_R = ControllerKey("B_COL1_R", 64)
    val B_COL2_R = ControllerKey("B_COL2_R", 65)
    val B_COL3_R = ControllerKey("B_COL3_R", 66)
    val B_COL4_R = ControllerKey("B_COL4_R", 67)
    val B_COL5_R = ControllerKey("B_COL5_R", 68)
    val B_COL6_R = ControllerKey("B_COL6_R", 69)
    val B_COL7_R = ControllerKey("B_COL7_R", 70)
    val B_COL8_R = ControllerKey("B_COL8_R", 71)

}